### ISSUE TITLE
Correct and Improve `PULL_REQUEST_TEMPLATE`

### ISSUE THREAD

**Issue by RedFox0x20** [margaritahumanitarian/helpafamily#194]
Currently we have `.github/PULL_REQUEST_TEMPLATE/pull_request_template.md` however I don't believe this has been put in the correct format, it may be necessary to format the data similar to the `.github/ISSUE_TEMPLATE/<some_template>.md` files using the following yaml
```yaml
---
name: Tracking issue
about: Use this template for tracking new features.
title: "[DATE]: [FEATURE NAME]"
labels: tracking issue, needs triage
assignees: octocat
---
```

However it may also be that this system only works as a part of the automation using the Query parameter.

Self assigned while reading through the documentation. If you know the answer to this one please leave a comment here so that the appropriate changes can be made.
